version: "3.9"
services:
  db:
    image: postgres:15
    container_name: electa-postgres
    environment:
      POSTGRES_USER: electa
      POSTGRES_PASSWORD: electa
      POSTGRES_DB: electa_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U electa -d electa_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: electa-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
