"""Add admin, candidate, and source tables

Revision ID: 08e1b4cea41c
Revises: ea1e60b7bb3d
Create Date: 2025-08-05 11:14:24.161523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e1b4cea41c'
down_revision = 'ea1e60b7bb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'DATA_EDITOR', 'MODERATOR', 'VERIFICATION_OFFICER', name='adminrole'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('vision_statement', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='profilestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('URL', 'PDF', 'IMAGE', name='sourcetype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('external_publisher_name', sa.String(), nullable=True),
    sa.Column('credibility_tier', sa.Enum('TIER_1_GOVERNMENT', 'TIER_2_NEWS_MEDIA', 'TIER_3_EXPERT', name='credibilitytier'), nullable=False),
    sa.Column('uploaded_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###