"""Add compliance evidence and record tables

Revision ID: 1c9d08902522
Revises: 4bf7e3aa3c6b
Create Date: 2025-08-06 10:55:14.244528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9d08902522'
down_revision = '4bf7e3aa3c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###