"""Add compliance evidence and record tables

Revision ID: 4bf7e3aa3c6b
Revises: 08e1b4cea41c
Create Date: 2025-08-06 10:36:50.783431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bf7e3aa3c6b'
down_revision = '08e1b4cea41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charterversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('review_deadline', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charterclauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('clause_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('clause_text_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clause_group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['charterversions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complianceevidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partycompliancerecords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('compliance_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'PARTIALLY_COMPLIANT', 'UNDER_REVIEW', 'NOT_APPLICABLE', name='compliancestatus'), nullable=False),
    sa.Column('public_notes', sa.String(), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_due_at', sa.DateTime(), nullable=True),
    sa.Column('assessed_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['clause_id'], ['charterclauses.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['complianceevidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partycompliancerecords_party_id'), 'partycompliancerecords', ['party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partycompliancerecords_party_id'), table_name='partycompliancerecords')
    op.drop_table('partycompliancerecords')
    op.drop_table('complianceevidence')
    op.drop_table('charterclauses')
    op.drop_table('charterversions')
    # ### end Alembic commands ###