"""Create initial v2.0 schema

Revision ID: ea1e60b7bb3d
Revises: 
Create Date: 2025-08-05 04:09:22.933944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea1e60b7bb3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('citizen_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', 'LOGIN_SUCCESS', 'LOGIN_FAIL', name='actiontype'), nullable=False),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('verification_status', sa.Enum('MOBILE_VERIFIED', 'PENDING_NID', 'NID_VERIFIED', 'REJECTED_NID', name='verificationstatus'), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'TRUSTED_CONTRIBUTOR', name='citizenrole'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizens_mobile_number'), 'citizens', ['mobile_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizens_mobile_number'), table_name='citizens')
    op.drop_table('citizens')
    op.drop_table('auditlogs')
    # ### end Alembic commands ###